from os import getenv
from dotenv import load_dotenv

load_dotenv()

STRING = getenv("STRING")
STRING2 = getenv("STRING2")
STRING3 = getenv("STRING3")
STRING4 = getenv("STRING4")
STRING5 = getenv("STRING5")
STRING6 = getenv("STRING6")
STRING7 = getenv("STRING7")
STRING8 = getenv("STRING8")
STRING9 = getenv("STRING9")
STRING10 = getenv("STRING 10")
STRING11 = getenv("STRING 11")
STRING12 = getenv("STRING 12")
STRING13 = getenv("STRING 13")
STRING14 = getenv("STRING 14")
STRING15 = getenv("STRING 15")
STRING16 = getenv("STRING 16")
STRING17 = getenv("STRING 17")
STRING18 = getenv("STRING 18")
STRING19 = getenv("STRING 19")
STRING20 = getenv("STRING 20")
STRING21 = getenv("STRING 21")
STRING22 = getenv("STRING 22")
STRING23 = getenv("STRING 23")
STRING24 = getenv("STRING 24")
STRING25 = getenv("STRING 25")
ALIVE_NAME = getenv("ALIVE_NAME")
USERNAME =getenv("USERNAME")
API_ID = getenv("API_ID")
API_HASH = getenv("API_HASH")
BIO_MESSAGE = getenv("BIO")
SUDO = list(map(int, getenv("SUDO").split()))
